#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ListApp.Resource", IsApplication=true)]

namespace ListApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::blocke.circleimageview.Resource.Attribute.civ_border_color = global::ListApp.Resource.Attribute.civ_border_color;
			global::blocke.circleimageview.Resource.Attribute.civ_border_overlay = global::ListApp.Resource.Attribute.civ_border_overlay;
			global::blocke.circleimageview.Resource.Attribute.civ_border_width = global::ListApp.Resource.Attribute.civ_border_width;
			global::blocke.circleimageview.Resource.Attribute.civ_fill_color = global::ListApp.Resource.Attribute.civ_fill_color;
			global::blocke.circleimageview.Resource.Styleable.CircleImageView = global::ListApp.Resource.Styleable.CircleImageView;
			global::blocke.circleimageview.Resource.Styleable.CircleImageView_civ_border_color = global::ListApp.Resource.Styleable.CircleImageView_civ_border_color;
			global::blocke.circleimageview.Resource.Styleable.CircleImageView_civ_border_overlay = global::ListApp.Resource.Styleable.CircleImageView_civ_border_overlay;
			global::blocke.circleimageview.Resource.Styleable.CircleImageView_civ_border_width = global::ListApp.Resource.Styleable.CircleImageView_civ_border_width;
			global::blocke.circleimageview.Resource.Styleable.CircleImageView_civ_fill_color = global::ListApp.Resource.Styleable.CircleImageView_civ_fill_color;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::ListApp.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::ListApp.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::ListApp.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::ListApp.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::ListApp.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::ListApp.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::ListApp.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::ListApp.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::ListApp.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::ListApp.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::ListApp.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::ListApp.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::ListApp.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::ListApp.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::ListApp.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::ListApp.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::ListApp.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::ListApp.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::ListApp.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::ListApp.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::ListApp.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			// aapt resource value: 0x7f010008
			public const int civ_border_color = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int civ_border_overlay = 2130771977;
			
			// aapt resource value: 0x7f010007
			public const int civ_border_width = 2130771975;
			
			// aapt resource value: 0x7f01000a
			public const int civ_fill_color = 2130771978;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int attention = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int avatar = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int check = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int clock = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int close = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int close_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int divider = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int important = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int kek = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int logo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int logout = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int logout_button = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int menu = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int password = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int people = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int pig = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int status = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int status_done = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int status_done_button = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int status_important = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int time = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int username = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int violet_button = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int ApliedButton = 2131034117;
			
			// aapt resource value: 0x7f05001c
			public const int Avatar = 2131034140;
			
			// aapt resource value: 0x7f050003
			public const int CancelButton = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int DataLayout = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int HeadLayout = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int IsAllDayRow = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int IsProorityTaskRow = 2131034128;
			
			// aapt resource value: 0x7f050022
			public const int ListView = 2131034146;
			
			// aapt resource value: 0x7f05001e
			public const int Mail = 2131034142;
			
			// aapt resource value: 0x7f050019
			public const int MenuButton = 2131034137;
			
			// aapt resource value: 0x7f050000
			public const int MvvmCrossTagId = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindingTagUnique = 2131034113;
			
			// aapt resource value: 0x7f05001d
			public const int Name = 2131034141;
			
			// aapt resource value: 0x7f050013
			public const int RecallForRow = 2131034131;
			
			// aapt resource value: 0x7f050007
			public const int SelectDateRow = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int SelectTimeRow = 2131034122;
			
			// aapt resource value: 0x7f050012
			public const int checkBox1 = 2131034130;
			
			// aapt resource value: 0x7f05000f
			public const int checkBox2 = 2131034127;
			
			// aapt resource value: 0x7f050015
			public const int editText1 = 2131034133;
			
			// aapt resource value: 0x7f05000c
			public const int editText2 = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int editText3 = 2131034121;
			
			// aapt resource value: 0x7f05001f
			public const int enablePushSwitch = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int enableSyncSwitch = 2131034144;
			
			// aapt resource value: 0x7f050023
			public const int img = 2131034147;
			
			// aapt resource value: 0x7f050021
			public const int logoutButton = 2131034145;
			
			// aapt resource value: 0x7f050017
			public const int myButton = 2131034135;
			
			// aapt resource value: 0x7f050024
			public const int name = 2131034148;
			
			// aapt resource value: 0x7f05001b
			public const int relativeLayout1 = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int settings = 2131034138;
			
			// aapt resource value: 0x7f050004
			public const int textView1 = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int textView11 = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int textView12 = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int textView13 = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int textView14 = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int textView15 = 2131034132;
			
			// aapt resource value: 0x7f050018
			public const int toolbar = 2131034136;
			
			// aapt resource value: 0x7f050016
			public const int webView = 2131034134;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int DescriptionTask = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Login = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Settings = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Sort = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int sort_list_item = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Custom = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircleImageView = new int[] {
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 1
			public const int CircleImageView_civ_border_color = 1;
			
			// aapt resource value: 2
			public const int CircleImageView_civ_border_overlay = 2;
			
			// aapt resource value: 0
			public const int CircleImageView_civ_border_width = 0;
			
			// aapt resource value: 3
			public const int CircleImageView_civ_fill_color = 3;
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
